//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationCriptomoneda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID_Venta { get; set; }
        public int ID_Cuenta { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
    }
}
